# RPM package for my-gpp-node
# This file is regularly AUTO-GENERATED by the IDE. DO NOT MODIFY.

# By default, the RPM will install to the standard REDHAWK SDR root location (/var/redhawk/sdr)
# You can override this at install time using --prefix /new/sdr/root when invoking rpm (preferred method, if you must)
%{!?_sdrroot: %define _sdrroot /var/redhawk/sdr}
%define _prefix %{_sdrroot}
Prefix: %{_prefix}

Name: my-gpp-node
Summary: Node my-gpp-node
Version: 1.0.0
Release: 1
License: None
Group: REDHAWK/Nodes
Source: %{name}-%{version}.tar.gz
# Require the device manager whose SPD is referenced
Requires: DeviceManager
# Require each referenced device/service
Requires: GPP
BuildArch: noarch
BuildRoot: %{_tmppath}/%{name}-%{version}

%description

%prep
%setup

%install
%__rm -rf $RPM_BUILD_ROOT
%__mkdir_p "$RPM_BUILD_ROOT%{_prefix}/dev/nodes/%{name}"
%__install -m 644 DeviceManager.dcd.xml $RPM_BUILD_ROOT%{_prefix}/dev/nodes/%{name}/DeviceManager.dcd.xml
%__install -m 644 DeviceManager.dcd.xml.template $RPM_BUILD_ROOT%{_prefix}/dev/nodes/%{name}/DeviceManager.dcd.xml.template
%__mkdir_p "$RPM_BUILD_ROOT%{_sysconfdir}/init.d"
%__install -m 755 etc/init.d/%{name} $RPM_BUILD_ROOT%{_sysconfdir}/init.d/%{name}

%files
%defattr(-,redhawk,redhawk)
%dir %{_prefix}/dev/nodes/%{name}
%config %{_prefix}/dev/nodes/%{name}/DeviceManager.dcd.xml
%{_prefix}/dev/nodes/%{name}/DeviceManager.dcd.xml.template
%attr(755, root, root) %{_sysconfdir}/init.d/%{name}
